### ISSUE TITLE
Will you open-source the 4D-aware video diffusion model mentioned in the paper?

### ISSUE THREAD

**Issue by ac635** [VITA-Group/Diffusion4D#10]
Thank you for sharing the dataset from this exceptional work. I am particularly interested in the 4D-aware video diffusion model mentioned in your paper and was wondering if there are any plans to open-source it. The results you’ve achieved are impressive, and incorporating the 4D-aware video diffusion model into my workflow would be incredibly valuable for my research. I would greatly appreciate it if you could consider releasing it. Thank you for your consideration.

**Comment by hw-liang** [comment]
Hi, thank you for your interest in our work. This work is still under review. We plan to release the code later.
