### ISSUE TITLE
ObjV1_all_animated.txt

### ISSUE THREAD

**Issue by Iron-LYK** [VITA-Group/Diffusion4D#12]
Hi, thanks for your great work! The instruction says that the uncurated 42k IDs of all the animated objects from objaverse-1.0 are in "rendering/src/ObjV1_all_animated.txt", but I didn't find this file, only "rendering/src/ObjV1_curated.txt". I would like to inquire where I can get this file, thanks!

**Comment by hw-liang** [comment]
Hi, thank you for your interest in our work. We are doing a manual check of the whole objaverse-1.0 animated data to remove very low quality assets. It will be done in a few days. Please expect a better quality, larger dynamic assets dataset. Thank you!
