### ISSUE TITLE
Download Objaverse-XL dataset error

### ISSUE THREAD

**Issue by iOscar03** [VITA-Group/Diffusion4D#3]
Thanks for your great work! 
I have encountered several different download errors while downloading the dataset using the "oxl.download_objects" API and some errors just directly terminate the download process. Have you ever encountered this problem? If you do, how did you solve it?

**Comment by YuyangYin** [comment]
Which one?

**Comment by iOscar03** [comment]
Here is an example error. Actually there are other errors for other objects(not for all), even though I skipped this github link/object, there will be new errors.
![image](https://github.com/VITA-Group/Diffusion4D/assets/143101802/53a72cb2-52b8-407d-8a80-c3eb605b65d0)

**Comment by Ir1d** [comment]
Hi @iOscar03, Thanks for your interest. We indeed observe similar issues when downloading the XL dataset. Our solution is to add a lot of `try...except` to the script to skip these failures. 
Hopefully I can share my render script (with try etc. added) early next week, but please feel free to skip those troublesome objects.

**Comment by iOscar03** [comment]
Thanks for your instant answer, this issue can be closed
