### ISSUE TITLE
xl data unzip error

### ISSUE THREAD

**Issue by zyk950607** [VITA-Group/Diffusion4D#6]
Using unzip and 7zz to uncompress the xl zips both get errors, for example, 7zz will get error that "ERROR: CRC Failed : xl_vita7.zip".
I don't know if it's the original file or the decompression tool. Can you offer some help？
Thank you.

**Comment by hw-liang** [comment]
For the xl dataset, the zip file is too large and it's split into multiple sections.  You can merge them before unzipping.
e.g. 
zip -FF 1.zip --out 1-full.zip
unzip -FF 1-full.zip

**Comment by Ir1d** [comment]
Hi @zyk950607 you can safely ignore the 'xl_vita7.zip'. It was included mistakenly and doesn't affect the rest of the xl data
