### ISSUE TITLE
evaluation set

### ISSUE THREAD

**Issue by jbji** [VITA-Group/Diffusion4D#7]
hi. thanks for this amazing work and data release. I wonder what 20 samples exactly did this work use for evaluation, which is important for fair comparison on evaluation metrics.

It seems that it's possibly the last 20 samples (can I confirm it?) of the provided id list, but it would be better if an additional evaluation id list can be provided.

**Comment by hw-liang** [comment]
Hi, thank you for your interests in our work. The released ids are lexicographically ordered and contain both train and evaluation splits. We leave out 20 animal- and human-centered assets for evaluation. We will release the ids later.
