### ISSUE TITLE
4D asset rendering using blender

### ISSUE THREAD

**Issue by fuxiao0719** [VITA-Group/Diffusion4D#8]
Hi, thanks for this great work as well as the rendered dataset!

I'm currently rendering 4D assets (your curated subset) using Blender into long video sequences (around 70+ frames). Since the mesh motion stops at a certain frame, I wonder if there is a way to detect when it stops or even keep the motion cycling. Super thanks!

**Comment by YuyangYin** [comment]
To be honest, we don't know how to detect stopping time. In some cases, the motion repeats several times. An easy way to handle this is to drop these cases using 'try-except'. If you find a better method, thanks for sharing.

**Comment by fuxiao0719** [comment]
Ok, thanks for the answer!
